name: Prakiraan Cuaca Harian Otomatis

on:
  # Trigger otomatis terjadwal (Setiap hari pukul 06:15 WIB / 23:15 UTC)
  schedule:
    - cron: '15 23 * * *'  
    
  # Trigger manual
  workflow_dispatch:         

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Jalankan skrip prakiraan dan Kirim Email
        # MEMANGGIL SKRIP PYTHON
        run: python main.py
        env:
          # Meneruskan GitHub Secrets
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}

      - name: Commit hasil gambar ke repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update Prakiraan Cuaca Harian'
          files: 'output_data/PrakicuITM.png' 
          branch: main
