name: Prakiraan Cuaca Harian Otomatis

# Kunci 'on:' harus berada di level 0 (sejajar dengan 'name:')
on:
  # Kunci 'schedule:' harus diindentasi 2 spasi di bawah 'on:' (Baris 4)
  schedule:
    - cron: '15 23 * * *'  
    
  workflow_dispatch:         

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # ... (lanjutan jobs)
