name: Prakiraan Cuaca Harian Otomatis

on:
  schedule:
    - cron: '15 23 * * *'   # Baris 5

  workflow_dispatch:         # Baris 7 (Pastikan 2 spasi di depan!)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Jalankan skrip prakiraan dan Kirim Email
        run: python prakicu_github.py
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}

      - name: Commit hasil gambar ke repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update Prakiraan Cuaca Harian'
          files: 'output_data/PrakicuITM.png' 
          branch: main
